trigger:
- master
pr:
- master
stages:
- stage: build_and_test
  displayName: Build And Test
  jobs:
  - job: application
    displayName: Application
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: UsePythonVersion@0
      displayName: Use Python 3.7.x
      inputs:
        versionSpec: 3.7.x
    - task: ShellScript@2
      displayName: Install Infrastructure Dependencies
      inputs:
        scriptPath: infra/pipeline/scripts/install-infrastructure-dependencies.sh
        cwd: $(System.DefaultWorkingDirectory)
        args: "$(ghtoken)"
        disableAutoCwd: true
    
- stage: deploy_application
  displayName: Deploy Application
  dependsOn: build_and_test
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: deploy_sbx
    displayName: Deploy Application to Sandbox
    pool:
      vmImage: ubuntu-16.04
    environment: sbx
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Artifacts
            inputs:
              artifact: pct-own
              path: $(System.ArtifactsDirectory)
          - task: UsePythonVersion@0
            displayName: Use Python 3.7.x
            inputs:
              versionSpec: 3.7.x
          - task: ShellScript@2
            displayName: Install Release Dependencies
            inputs:
              scriptPath: $(System.ArtifactsDirectory)/infra/pipeline/scripts/install-release-dependencies.sh
              args: "$(ghtoken)"
              cwd: $(System.ArtifactsDirectory)
              disableAutoCwd: true
          - task: AWSShellScript@1
            displayName: Create Or Update Stack
            inputs:
              awsCredentials: AWS-techintheburbs
              regionName: us-east-1
              arguments: $(System.ArtifactsDirectory)
              filePath: $(System.ArtifactsDirectory)/infra/pipeline/scripts/create-or-update-stack.sh
              cwd: $(System.ArtifactsDirectory)
              disableAutoCwd: true
